name: Deployment - Functions - Production

on:
  workflow_dispatch

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    environment: Production
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: |
          cd backend/functions
          npm ci
          cd ..

      - name: Create AWS Credentials File
        run: |
          cd backend/functions/src/provider
          echo "export const awsCredentials = {" > awsSecret.ts
          echo "  accessKeyId: '$${{secrets.AWS_ACCESS_KEY_ID}}'," >> awsSectet.ts
          echo "  secretAccessKey: '$${{secrets.AWS_SECRET_ACCESS_KEY}}'," >> awsSectet.ts
          echo "  role: '$${{secrets.AWS_IAM_ROLE_ARN}}'," >> awsSectet.ts
          echo "  region: '$${{secrets.AWS_REGION}}'," >> awsSectet.ts
          echo "};" >> awsSectet.ts
          cd ../../../..

      - name: Prepare Google Deployment Credentials
        run: |
          cd backend
          echo "${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}" | base64 --decode > "google-application-credentials.json"
          cd ..

      - name: Install Firebase CLI
        run: |
          cd backend/functions
          npm install -g firebase-tools
          cd ..

      - name: Deploy Firebase Functions
        run: |
          cd backend
          firebase deploy --only functions --non-interactive --force --project ${{vars.PROJECT_ID}}
          cd ..

      - name: Remove files
        run: |
          rm backend/google-application-credentials.json
