name: Deployment - Functions - Production

on:
  workflow_dispatch

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    environment: Production
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: |
          cd backend/functions
          npm ci
          cd ..

      - name: Prepare Google Deployment Credentials
        run: |
          cd backend
          echo "${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}" | base64 --decode > "google-application-credentials.json"
          cd ..

      - name: Install Firebase CLI
        run: |
          cd backend/functions
          npm install -g firebase-tools
          cd ..

      - name: Deploy Firebase Functions
        run: |
          cd backend
          firebase deploy --only functions --non-interactive --force --project ${{vars.PROJECT_ID}}
          cd ..

      - name: Remove files
        run: |
          rm backend/google-application-credentials.json
